# Literature Review

Due to the raising popularity in recent years of cryptocurrency, there has been a lot of research related to digital currency, from which the field of asset pricing is no exception. The latter because there is a growing interest related to the study of the factors that affect the returns of this type of assets, which certainly translates into a lot of studies whose objective is the previously mentioned. While the research topics may seem similar, it is important to note that this allows for a comprehensive categorization of the studies, despite the broadness of the related research.

The first group corresponds to the empirical studies that test for the performance of widely accepted asset pricing models such as the CAPM \cite{sharpe1964}, FF3 \cite{fama1993}, FF5 \cite{fama2015}, Carhart \cite{carhart1997}, among others. The methodology is based on the recollection of data related to returns on a specific set of cryptocurrencies in a particular time period, to then calculate the factors of the models mentioned previously. Due to the great amount of investigation that follows said framework, there are also a lot of studies that in addition to the steps mentioned previously, they complement the study with techniques that help understand better the underlying phenomena. For the better understanding of these groups of studies, some will be discussed that will most definitely aid the current investigation.

A first study that is included in the group of empirical studies is the one done by \cite{gregoriou2019cryptocurrencies}. In this investigation they demonstrate that investors obtain abnormal excess returns on the London Stock Exchange from the years 2014 to 2017. The main reason behind was because of earlier studies, like \cite{bariviera2017inefficiency}, that found evidence of inefficiency and the lack of regulation related to the cryptocurrency market. The data used corresponds to daily returns of all London Stock Exchange listed securities from the years 2014-2017, where they conclude that, applying CAPM, FF3, Carhart, and FF5, investors do indeed obtain excess returns by speculating in cryptocurrencies. suggesting that they are inefficient. While this memoir primarily does not explore into the efficiency of cryptocurrency markets, the insights from \cite{gregoriou2019cryptocurrencies} underline the broad applicability and versatility of such studies.

Another study is the one done by \cite{liu2022common}, where they find that there are three factors that capture the cross-sectional expected cryptocurrency returns. Despite not forming part of the gross of the investigation, this study mentions a very interesting aspect corresponding to the different opinions people have related to cryptocurrency; they say there are two views about the related market. The first one says that all coins represent bubbles and fraud. And, the second states the technology behind said markets may become an important innovation and that at least some coins may become assets that represent stake in the future of the related technology \cite{liu2022common}. With the current information of cryptocurrency markets it is difficult to establish right from wrong with respect to said opinions, but either way, empirical studies like \cite{liu2022common} contribute largely to understand the factors that better explain the returns of corresponding assets. Now, regarding the research itself, the factors studied were cryptocurrency size, momentum, volume, and volatility. It is important to mention that the study focus only on said market-factors, because financial and accounting data was not available for the cross section of the coins that were analyzed in the data.

Regarding the conclusions drawn from said investigation, there are several to consider. Firstly, that size and momentum factors well capture the cross-section of cryptocurrnecy returns. Furthermore, a three-factor model can be constructed using market information is successful in pricing the strategies in the cryptocurrency market. A number of theoretical explanations are drawn for the factors. In relation to the cryptocurrency size premium\footnote{Smaller, less established cryptocurrencies may offer higher potential returns to compensate for their higher risk \cite{Statista2023}.}; the cryptocurrency size factor relates to the liquidity effect\footnote{Referring to the ease with which a digital currency or token can be converted to another digital asset or cash without impacting the price and vice-versa \cite{CFI_nodate}.}. Secondly, they find some evidence that the size premium is consistent with a mechanism proposed by cryptocurrency theories: the trade-off between capital gains and the convenience yield.

As to momentum, the conclusions show that they are in line with the investor overreaction channel, indicating the tendency of investors to react disproportionately to new information, which in turn causes the price of cryptocurrency to swing more than it should according to its intrinsic value \cite{10.1371/journal.pone.0264522}.
Continuing the line of empirical validation studies, \cite{thoma2020prospect} investigated whether an investing strategy modeled by a prospect theory leads to a risk-adjusted outperformance, based on different factor models which include the \cite{fama1993}. The utilization of prospect theory fits well in modeling the way investors inform themselves about a certain cryptocurrency, since they usually look at the price chart and then mentally represent a historical return distribution. So, according to \cite{thoma2020prospect}, by looking a the price chart of cryptocurrency, investors evaluate the skeweness\footnote{Measure of the asymmetry of a distribution.} and evaluate the asset as a gamble, similar to lottery. The conclusions imply that cryptocurrency holders choose high prospect theory values over low values, with investors generally favoring the latter. Due to this predilection, cryptocurrencies with high prospect theory values are overbought, which reduces future gains. Cryptocurrencies with low prospect theory values, on the other hand, are less likely to be overbought and might result in larger future returns.

While the previous study presented did not place significant emphasis on the regression models themselves, it uses said models as a complement of the main model of the investigation, which was the prospect theory model.\\
Another approach to the asset pricing of cryptocurrency is the one taken by \cite{HAYES20171308}, where a regression model is estimated using cost of production factors, rather than the usual market factors that comprise the most popular asset pricing models. Concerning the factors, \cite{HAYES20171308} concludes that more than 84\% of value formation can be explained by three variables: computational power (as a representative for mining difficulty), rate of coin production, and the relative hardness of the mining algorithm employed.